/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TelegraphRouteImport } from './routes/telegraph'
import { Route as LabRouteImport } from './routes/lab'
import { Route as DossierRouteImport } from './routes/dossier'
import { Route as ChronicleRouteImport } from './routes/chronicle'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as IndexRouteImport } from './routes/index'

const TelegraphRoute = TelegraphRouteImport.update({
  id: '/telegraph',
  path: '/telegraph',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const DossierRoute = DossierRouteImport.update({
  id: '/dossier',
  path: '/dossier',
  getParentRoute: () => rootRouteImport,
} as any)
const ChronicleRoute = ChronicleRouteImport.update({
  id: '/chronicle',
  path: '/chronicle',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/chronicle': typeof ChronicleRoute
  '/dossier': typeof DossierRoute
  '/lab': typeof LabRoute
  '/telegraph': typeof TelegraphRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/chronicle': typeof ChronicleRoute
  '/dossier': typeof DossierRoute
  '/lab': typeof LabRoute
  '/telegraph': typeof TelegraphRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cases': typeof CasesRoute
  '/chronicle': typeof ChronicleRoute
  '/dossier': typeof DossierRoute
  '/lab': typeof LabRoute
  '/telegraph': typeof TelegraphRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cases' | '/chronicle' | '/dossier' | '/lab' | '/telegraph'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cases' | '/chronicle' | '/dossier' | '/lab' | '/telegraph'
  id:
    | '__root__'
    | '/'
    | '/cases'
    | '/chronicle'
    | '/dossier'
    | '/lab'
    | '/telegraph'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CasesRoute: typeof CasesRoute
  ChronicleRoute: typeof ChronicleRoute
  DossierRoute: typeof DossierRoute
  LabRoute: typeof LabRoute
  TelegraphRoute: typeof TelegraphRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/telegraph': {
      id: '/telegraph'
      path: '/telegraph'
      fullPath: '/telegraph'
      preLoaderRoute: typeof TelegraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossier': {
      id: '/dossier'
      path: '/dossier'
      fullPath: '/dossier'
      preLoaderRoute: typeof DossierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chronicle': {
      id: '/chronicle'
      path: '/chronicle'
      fullPath: '/chronicle'
      preLoaderRoute: typeof ChronicleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CasesRoute: CasesRoute,
  ChronicleRoute: ChronicleRoute,
  DossierRoute: DossierRoute,
  LabRoute: LabRoute,
  TelegraphRoute: TelegraphRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
